name: Pull, build, tag and push to Docker Registry

on:
  push:
    branches:
      - main

jobs:
  os_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [16, 18, 20]
    runs-on: ${{ matrix.os }}

  # checkout:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #           sparse-checkout: .
  #           ref: main

  # build:
  #   permissions:
  #       contents: read
  #       packages: write
  #       attestations: write
  #       id-token: write
     
  #   runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            sparse-checkout: .
            ref: main
      
      - name: Set up Node.js ${{ matrix.version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
          cache: 'npm'
      
      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci
      
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
  
      - name: Run tests
        run: npm test

      - name: Cache docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.docker-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          cache-from: type=local,src=/tmp/.docker-cache
          cache-to: type=local,dest=/tmp/.docker-cache-new
          tags: ghcr.io/${{ github.repository }}:latest
      
      - name: Move cache
        run: |
          rm -rf /tmp/.docker-cache
          mv /tmp/.docker-cache-new /tmp/.docker-cache
        shell: bash

