name: Multi-platform & Multi-version Testing

on:
  push:
    branches:
      - main

jobs:
    os_matrix:
        strategy:
          matrix:
            os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  sparse-checkout: .
                  ref: main
            
            - name: Set up Node.js ${{ matrix.version }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.version }}
                cache: 'npm'  # NPM Caching for faster dependency installs.
            - run: npm ci
            - run: npm run build --if-present
            - run: npm test